name: Create Tag on Merge

on:
  push:
    branches:
      - main  # Cambia 'main' a la rama a la que se hacen los merges

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git user
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Create Tag
        run: |
          # Obtén el hash del último commit
          COMMIT_HASH=$(git rev-parse --short HEAD)
          
          # Crea un nuevo tag con el hash del commit como parte del nombre del tag
          git tag "merge-${COMMIT_HASH}"
          
          # Hace push del tag al repositorio remoto
          git push origin --tags